In [5]:
import numpy as np
import primate

In [7]:
import cupyx 
import cupy as cp

In [38]:
N = int(1e7)
x_pin = cupyx.zeros_pinned(N, dtype=np.int64)
x_dev = cp.zeros(N, dtype=np.int64)

In [42]:
from cupyx.profiler import benchmark
def get_dev():
    # return x_dev.get()
    return cp.asnumpy(x_dev)
def get_pin():
    return cp.asnumpy(x_pin)

In [43]:
print(benchmark(get_dev, n_repeat=200)) 

get_dev             :    CPU: 98305.967 us   +/- 2009.629 (min: 93433.388 / max: 112549.486) us     GPU-0: 98336.877 us   +/- 2012.635 (min: 93457.603 / max: 112587.837) us


In [44]:
print(benchmark(get_pin, n_repeat=200)) 

get_pin             :    CPU:     0.694 us   +/-  1.599 (min:     0.505 / max:    23.233) us     GPU-0:     3.304 us   +/-  1.691 (min:     2.752 / max:    26.880) us


In [32]:
print(cp.asnumpy(x_pin))

[0 0 0 ... 0 0 0]


In [46]:
x_dev

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
x_cpu = x_dev.get()
print(x_cpu)

[0 0 0 ... 0 0 0]
